CREATE TABLE Books
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY,
	[NameBook] NVARCHAR(100) NOT NULL,
	[Author] NVARCHAR(100) NOT NULL,
	[Category] NVARCHAR(50) NOT NULL,
	[Price] DECIMAL(16, 2) NOT NULL
)